### ISSUE TITLE
Undefined method 'path'

### ISSUE THREAD

**Issue by mperham** [rubyzip/rubyzip#119]
I'm just doing this where `det.content` is a String of binary data.

``` ruby
Zip::File.open_buffer(det.content) do |zipfile|
end
```

```
     NoMethodError:
       undefined method `path' for #<StringIO:0x007fe9036804e0>
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/entry.rb:180:in `read_c_dir_entry'
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/central_directory.rb:124:in `block in read_central_directory_entries'
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/central_directory.rb:123:in `times'
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/central_directory.rb:123:in `read_central_directory_entries'
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/central_directory.rb:135:in `read_from_stream'
     # ./.bundle/ruby/2.0.0/gems/rubyzip-1.1.0/lib/zip/file.rb:128:in `open_buffer'
```

**Comment by aalvarado** [comment]
Please check if setting the encoding in your StringIO object solves the issue, it did for me on a related issue:

https://github.com/rubyzip/rubyzip/issues/177#issuecomment-206030028
