### ISSUE TITLE
Error when calling Zip::File.open_buffer(io)

### ISSUE THREAD

**Issue by davidblondeau** [rubyzip/rubyzip#146]
Just updated from 1.1.0 to 1.1.2 and it seems like the call to reopen in OutputStream is causing an issue.

If you run the following code after replacing "something.zip" with the path to an actual file, you get the error that follows.

```
File.open("something.zip") do |io|
  io.set_encoding(Encoding::BINARY)
  Zip::File.open_buffer(io) do |zip_io|
    // left empty on purpose
  end
end
```

```
ArgumentError: wrong number of arguments (0 for 1..2)
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:32:in `reopen'
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:32:in `initialize'
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:59:in `new'
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/output_stream.rb:59:in `write_buffer'
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/file.rb:316:in `write_buffer'
    from vendor/ruby/1.9.1/gems/rubyzip-1.1.2/lib/zip/file.rb:128:in `open_buffer'
    from (irb):21:in `block in irb_binding'
    from (irb):19:in `open'
    from (irb):19
    from /Users/work/.rvm/rubies/ruby-1.9.3-p484/bin/irb:12:in `<main>'
```

**Comment by jdleesmiller** [comment]
I think this was fixed some time ago, but to be safe I have added a test case, which presently passes:

https://github.com/rubyzip/rubyzip/blob/eeef5073d58253e2044dbf81d1b205efd590b59a/test/file_test.rb#L134-L141

So, I'll close this out.
