### ISSUE TITLE
Problem with open_buffer

### ISSUE THREAD

**Issue by sandrods** [rubyzip/rubyzip#177]
I'm getting `undefined method `bytesize' for nil:NilClass`using open_buffer.

this code works:

``` ruby
data = string_with_zip_file
::File.open('my_file.zip', "wb") {|f| f.write(data) }
Zip::File.open('my_file.zip')
```

but if I try to use open_buffer

``` ruby
data = string_with_zip_file
Zip::File.open_buffer(data)
```

I get this error:

```
NoMethodError: NoMethodError: undefined method `bytesize' for nil:NilClass
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry.rb:224:in `read_local_entry'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry.rb:194:in `read_local_entry'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/output_stream.rb:114:in `block in copy_raw_entry'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry.rb:557:in `get_raw_input_stream'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/output_stream.rb:112:in `copy_raw_entry'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry.rb:545:in `write_to_zip_output_stream'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/file.rb:318:in `block (2 levels) in write_buffer'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry_set.rb:42:in `call'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry_set.rb:42:in `block in each'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry_set.rb:41:in `each'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/entry_set.rb:41:in `each'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/file.rb:318:in `block in write_buffer'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/output_stream.rb:60:in `write_buffer'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/file.rb:317:in `write_buffer'
  .rbenv/versions/1.9.3-p327/.../rubyzip-1.1.6/lib/zip/file.rb:128:in `open_buffer'
```

Am I doing something wrong?

**Comment by kylekyle** [comment]
It looks like this is not going to be fixed. Can a project maintainer just mark it as such and make the method private so people aren't led to believe they can open a buffer directly?

**Comment by aalvarado** [comment]
I was getting this error while trying to use the Roo gem.

It looks like it was an encoding issue. We had something like this:

```ruby
Roo::Excelx.new(StringIO.new(xlsx_report.file_data))
```
and getting

```
NoMethodError:
       undefined method `bytesize' for nil:NilClass
```

loading it like this:

```ruby
Roo::Excelx.new(StringIO.new(xlsx_report.file_data).set_encoding('ASCII-8BIT'))
```

solves the issue.

**Comment by bpina** [comment]
I received this error as well, but it only occurred when I ran the code on OS X. There was no problem opening the file on Linux (Gentoo or Ubuntu). 

Here's some example code that could reproduce the problem on OS X:
```ruby
Zip::File.open_buffer(File.read('/path/to/my_zip.zip'))
```

I was able to resolve the issue on OS X by changing my code to:
```ruby
Zip::File.open_buffer(File.binread('/path/to/my_zip.zip'))
```

**Comment by hainesr** [comment]
Fixed, as far as I can tell.
