### ISSUE TITLE
IO class is not properly supported for streaming.

### ISSUE THREAD

**Issue by weshatheleopard** [rubyzip/rubyzip#192]
Change the code at the following location ( https://github.com/rubyzip/rubyzip/blob/05916bf89181e1955118fd3ea059f18acac28cc8/test/file_test.rb#L538 ) to be as follows:

```
File.open(zname, 'rb') { |f|
  Zip::File.open_buffer(f) do |zipfile|
  end
}
```

According to the documentation, IO object is valid in this situation. However, the modified test fails:

```
ZipFileTest#test_streaming:
ArgumentError: wrong number of arguments (0 for 1..2)
    /mnt/var/git/rubyzip/lib/zip/output_stream.rb:32:in `reopen'
    /mnt/var/git/rubyzip/lib/zip/output_stream.rb:32:in `initialize'
    /mnt/var/git/rubyzip/lib/zip/output_stream.rb:59:in `new'
    /mnt/var/git/rubyzip/lib/zip/output_stream.rb:59:in `write_buffer'
    /mnt/var/git/rubyzip/lib/zip/file.rb:317:in `write_buffer'
    /mnt/var/git/rubyzip/lib/zip/file.rb:128:in `open_buffer'
    /mnt/var/git/rubyzip/test/file_test.rb:542:in `block in test_streaming'
    /mnt/var/git/rubyzip/test/file_test.rb:541:in `open'
    /mnt/var/git/rubyzip/test/file_test.rb:541:in `test_streaming'
```

Also see related #177.

**Comment by jdleesmiller** [comment]
I think this is the same as https://github.com/rubyzip/rubyzip/issues/146 and now fixed.
