### ISSUE TITLE
Doesn't work on Ruby 2.2 and Rails 4.2

### ISSUE THREAD

**Issue by brunofrank** [rubyzip/rubyzip#229]
I follow the manual, installed rubyzip but the gem ins't loaded, it doesn't work, when i try direct on irb they work correctly.

LoadError: cannot load such file -- zip

Thanks.

**Comment by simonoff** [comment]
Can you post your Gemfile and Gemfile.lock ?

**Comment by brunofrank** [comment]
GemFile
```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.1.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-passenger'
  gem "letter_opener"
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'  
end

group :test do
  gem 'capybara'
  gem "capybara-webkit"
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'timecop'  
end

gem 'simple_form'
gem 'carrierwave'
gem 'rmagick'
gem "enumerate_it"
gem 'will_paginate', '~> 3.0'
gem 'delayed_job_active_record'
gem "delayed_job_web"
gem "daemons"
gem 'request_store'
gem "chartkick"
gem 'rqrcode'
gem 'cielo', git: 'https://github.com/crafters/cielo'
gem 'brcobranca'
gem 'nprogress-rails'
gem "opbeat", "~> 2.0"
gem 'agendor-ruby', git: 'https://github.com/ResultadosDigitais/agendor-ruby.git'
gem 'gcm'
gem 'activerecord-session_store'
gem 'rubyzip'
```

Gemfile.lock

```ruby

GIT
  remote: https://github.com/ResultadosDigitais/agendor-ruby.git
  revision: a221e14a27c85f3861ab6b9b650979cdc73f7534
  specs:
    agendor-ruby (1.0.1)
      httparty

GIT
  remote: https://github.com/crafters/cielo
  revision: 0db9bfcc20d88d614cbed149c1850c7f8f2624ce
  specs:
    cielo (0.1.5)
      activesupport (>= 3.0.7)
      builder (>= 2.0.0)
      i18n

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.0)
      actionview (= 4.2.0)
      activesupport (= 4.2.0)
      rack (~> 1.6.0)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    activejob (4.2.0)
      activesupport (= 4.2.0)
      globalid (>= 0.3.0)
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activerecord-session_store (0.1.1)
      actionpack (>= 4.0.0, < 5)
      activerecord (>= 4.0.0, < 5)
      railties (>= 4.0.0, < 5)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.7)
    arel (6.0.0)
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    brcobranca (4.0.0)
      activemodel (>= 3)
      parseline (~> 1.0.3)
      rghost (= 0.9.5)
      rghost_barcode (~> 0.9)
    builder (3.2.2)
    byebug (3.5.1)
      columnize (~> 0.8)
      debugger-linecache (~> 1.2)
      slop (~> 3.6)
    capistrano (3.3.5)
      capistrano-stats (~> 1.1.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-passenger (0.0.2)
      capistrano (~> 3.0)
    capistrano-rails (1.1.2)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-stats (1.1.1)
    capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-webkit (1.5.0)
      capybara (>= 2.3.0, < 2.5.0)
      json
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    chartkick (1.3.2)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1)
    colorize (0.7.5)
    columnize (0.9.0)
    daemons (1.1.9)
    debug_inspector (0.0.2)
    debugger-linecache (1.2.0)
    delayed_job (4.0.6)
      activesupport (>= 3.0, < 5.0)
    delayed_job_active_record (4.0.3)
      activerecord (>= 3.0, < 5.0)
      delayed_job (>= 3.0, < 4.1)
    delayed_job_web (1.2.10)
      activerecord (> 3.0.0)
      delayed_job (> 2.0.3)
      sinatra (>= 1.4.4)
    enumerate_it (1.2.4)
      activesupport (>= 3.0.0)
    erubis (2.7.0)
    execjs (2.3.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    gcm (0.1.0)
      httparty
      json
    globalid (0.3.3)
      activesupport (>= 4.1.0)
    hike (1.2.3)
    httparty (0.13.3)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    jbuilder (2.2.8)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.3)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.2)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.3.0)
      launchy (~> 2.2)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.4.3)
    mini_portile (0.6.2)
    minitest (5.5.1)
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mysql2 (0.3.18)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    nprogress-rails (0.1.6.6)
    opbeat (2.0.0)
      faraday (>= 0.7.6, < 0.10)
      multi_json (~> 1.0)
    parseline (1.0.3)
    rack (1.6.0)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.5)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.1)
      loofah (~> 2.0)
    railties (4.2.0)
      actionpack (= 4.2.0)
      activesupport (= 4.2.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
      json (~> 1.4)
    request_store (1.1.0)
    rghost (0.9.5)
    rghost_barcode (0.9)
    rmagick (2.13.4)
    rqrcode (0.4.2)
    rubyzip (1.1.7)
    sass (3.4.12)
    sass-rails (5.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (~> 1.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    shoulda-matchers (2.8.0)
      activesupport (>= 3.0.0)
    simple_form (3.1.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    slop (3.6.0)
    spring (1.3.2)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sshkit (1.6.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    timecop (0.7.3)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.0)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.0.0)
      activemodel (~> 4.0)
      binding_of_caller (>= 0.7.2)
      railties (~> 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    will_paginate (3.0.7)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-session_store
  agendor-ruby!
  bcrypt (~> 3.1.7)
  brcobranca
  byebug
  capistrano
  capistrano-bundler
  capistrano-passenger
  capistrano-rails
  capybara
  capybara-webkit
  carrierwave
  chartkick
  cielo!
  daemons
  delayed_job_active_record
  delayed_job_web
  enumerate_it
  factory_girl_rails
  gcm
  jbuilder (~> 2.0)
  jquery-rails
  letter_opener
  mysql2
  nprogress-rails
  opbeat (~> 2.0)
  rails (= 4.2.0)
  request_store
  rmagick
  rqrcode
  rubyzip
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  shoulda-matchers
  simple_form
  spring
  timecop
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
  will_paginate (~> 3.0)
```

**Comment by jozefvaclavik** [comment]
just a hint.. check your backtrace:

```
/Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- zip/zip (LoadError)
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/axlsx-1.3.6/lib/axlsx.rb:26:in `<top (required)>'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:247:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/axlsx_rails-0.1.5/lib/axlsx_rails.rb:1:in `<top (required)>'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
	from /Users/jozefvaclavik/App/config/application.rb:13:in `<top (required)>'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/jozefvaclavik/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

To me it was older version of axlsx gem that required zip/zip.. so check your dependencies..
```
    axlsx (1.3.6)
      htmlentities (~> 4.3.1)
      nokogiri (>= 1.4.1)
      rubyzip (>= 0.9.5)
```
