### ISSUE TITLE
Produces files it can't unzip

### ISSUE THREAD

**Issue by damncabbage** [rubyzip/rubyzip#247]
This script:

``` ruby
require 'zip'

passing_size = 65535
failing_size = 65536

[passing_size, failing_size].each do |size|
  print "Size: #{size} - "
  file = File.join(File.dirname(__FILE__), "testfile-#{size}.bin")
  zip  = File.join(File.dirname(__FILE__), "testfile-#{size}.zip")

  data_write = "z" * size
  filename   = "a" * size
  print "Gen'd, "

  File.open(file, 'wb') { |f| f.write(data_write) }
  print "Written, "

  Zip::File.open(zip, Zip::File::CREATE) { |f| f.add(filename, file) }
  print "Zipped, "

  data_read = nil
  Zip::File.open(zip) { |f| data_read = f.first.get_input_stream.read }
  print "Unzipped. "

  puts (data_write == data_read ? "Written data equals read data" : "Written data DOES NOT EQUAL read data")
end
```

... when written to `test_case.rb` and run with the following in a checkout of revision 04714ece9a (rubyzip's current master):

```
/path/to/clone-of-rubyzip-master$
/path/to/clone-of-rubyzip-master$ bundle exec ruby test_case.rb
```

... consistently produces this output:

```
Size: 65535 - Gen'd, Written, Zipped, Unzipped. Written data equals read data
Size: 65536 - Gen'd, Written, Zipped, /path/to/clone-of-rubyzip-master/lib/zip/inflater.rb:44:in `inflate': invalid stored block lengths (Zlib::DataError)
    from /path/to/clone-of-rubyzip-master/lib/zip/inflater.rb:44:in `internal_produce_input'
    from /path/to/clone-of-rubyzip-master/lib/zip/inflater.rb:15:in `sysread'
    from /path/to/clone-of-rubyzip-master/lib/zip/input_stream.rb:82:in `sysread'
    from /path/to/clone-of-rubyzip-master/lib/zip/ioextras/abstract_input_stream.rb:33:in `read'
    from test_case.rb:23:in `block (2 levels) in <main>'
    from /path/to/clone-of-rubyzip-master/lib/zip/file.rb:102:in `open'
    from test_case.rb:23:in `block in <main>'
    from test_case.rb:7:in `each'
    from test_case.rb:7:in `<main>'
```

**Comment by hainesr** [comment]
The ZIP standard only allows 2 bytes for storing the filename length so I guess we're not checking this at creation time and preventing overlong names. Will check this out.
