### ISSUE TITLE
TypeError: can't dup NilClass when opening a non-zip file

### ISSUE THREAD

**Issue by ProGM** [rubyzip/rubyzip#284]
My Rails application tried to open a RAR file uploaded by an user.

I expected to receive some kind of `Zip::Error`. Instead I got this:

```ruby
TypeError: can't dup NilClass
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `dup'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `block in dup'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `each'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `map'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `dup'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/file.rb:84:in `initialize'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in `new'
  from /usr/local/bundle/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in `open'
  from (irb):8
  from /usr/local/bundle/gems/railties-4.2.5.2/lib/rails/commands/console.rb:110:in `start'
  from /usr/local/bundle/gems/railties-4.2.5.2/lib/rails/commands/console.rb:9:in `start'
  from /usr/local/bundle/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /usr/local/bundle/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /usr/local/bundle/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
```

I'm using rubyzip 1.1.7

Since I can't find the changelog for rubyzip 1.2, I don't know if it was already fixed.

**Comment by ProGM** [comment]
Fixed upgrading to 1.2.0 :+1:
