### ISSUE TITLE
File has zero size error

### ISSUE THREAD

**Issue by solloron1** [rubyzip/rubyzip#285]
Hello,

I am getting an error that a 'file has zero size. Did you mean to pass the create flag?'.

I am using the roo gem (I have also tested it with rubyXL) for xlsx manipulation.  I have setup an EventMachine that pushes the contents of the cells to a dashboard and it works fine if I save it locally.  As soon as I move the same file that has been modified into the directory where it resides or upload it via ftp I get the below error.  What do I need to do to resolve this?

```
/home/solloron1/.gem/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:83:in `initialize': File /home/solloron1/dev/ruby/donn/sales.xlsx has zero size. Did you mean to pass the create flag? (Zip::Error)
    from /home/solloron1/.gem/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `new'
    from /home/solloron1/.gem/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `open'
    from /home/solloron1/.gem/ruby/2.3.0/gems/roo-2.3.2/lib/roo/excelx.rb:373:in `process_zipfile'
    from /home/solloron1/.gem/ruby/2.3.0/gems/roo-2.3.2/lib/roo/excelx.rb:48:in `initialize'
    from /home/solloron1/dev/ruby/donn/jobs/test.rb:16:in `new'
    from /home/solloron1/dev/ruby/donn/jobs/test.rb:16:in `fetch_spread'
    from /home/solloron1/dev/ruby/donn/jobs/test.rb:38:in `file_modified'
    from /home/solloron1/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/em/file_watch.rb:24:in `receive_data'
    from /home/solloron1/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /home/solloron1/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:87:in `start'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
    from /home/solloron1/.gem/ruby/2.3.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
    from /home/solloron1/.gem/ruby/2.3.0/bin/thin:23:in `load'
    from /home/solloron1/.gem/ruby/2.3.0/bin/thin:23:in `<main>'
```

**Comment by ShieldLord** [comment]
have the same problem

**Comment by yashdave00** [comment]
same issue

**Comment by hainesr** [comment]
@yashdave00 which version of rubyzip are you using?

**Comment by yashdave00** [comment]
i started  a zip output stream and it worked for me.
```
zipfile_name` = "zipped.zip"
  temp_file = Tempfile.new(zipfile_name)
 Zip::OutputStream.open(temp_file) {|zos|}
```
then i called the open function
` Zip::File.open(temp_file, Zip::File::CREATE) do |zipfile|`

**Comment by hainesr** [comment]
Did you call `Zip::File.open(temp_file, Zip::File::CREATE)` on the file you just created with `Zip::OutputStream.open(temp_file)` ?

**Comment by yashdave00** [comment]
Yes` temp_file` is the name of the file

**Comment by hainesr** [comment]
You shouldn't call `Zip::File.open` with the `CREATE` flag if the file exists already. Can you try with just `Zip::File.open(temp_file) do ....` instead?

**Comment by yashdave00** [comment]
I tried it and i did work
