### ISSUE TITLE
Zip::Error: Zip end of central directory signature not found - reading an xlsx file

### ISSUE THREAD

**Issue by airblade** [rubyzip/rubyzip#288]
I'm using rubyzip 1.2.0 on ruby 2.1.3.  When I try to read an xlsx file I get the following error:

``` ruby
[1] pry(main)> Zip::File.open "/path/to/file.xlsx"
Zip::Error: Zip end of central directory signature not found
from /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/central_directory.rb:143:in `get_e_o_c_d'
[2] pry(main)> wtf?
Exception: Zip::Error: Zip end of central directory signature not found
--
0: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/central_directory.rb:143:in `get_e_o_c_d'
1: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/central_directory.rb:103:in `read_e_o_c_d'
2: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/central_directory.rb:136:in `read_from_stream'
3: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/file.rb:77:in `block in initialize'
4: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/file.rb:76:in `open'
5: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/file.rb:76:in `initialize'
6: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `new'
7: /Users/andy/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `open'
8: (pry):1:in `__pry__'
```

The `file` command (on OS X 10.11.4) produces this:

```
$ file --mime file.xlsx
file.xlsx: CDF V2 Document, No summary info; charset=binary
```

I attach the file in question.

Thanks for your help!

[file.xlsx](https://github.com/rubyzip/rubyzip/files/204265/file.xlsx)

P.S. Numbers.app can open the file without any problems.  I don't have Excel to try with.

**Comment by gorn** [comment]
I can not open the file in Excel. To my experience it is much safer to use OpenDocument format once you are outside Microsoft niche.

**Comment by airblade** [comment]
If Excel won't open the file then that's that...though it's interesting than Numbers.app can.

**Comment by gorn** [comment]
xlsx in not greatest format to implement, so with exception of (maybe) Microsoft software I would use ods in everything else. Just my opinion.

**Comment by airblade** [comment]
Unfortunately the files are provided by 3rd parties and I have no control over them.

**Comment by gorn** [comment]
@airblade  That is life :) Good luck.
