### ISSUE TITLE
xslx file: undefined method `bytesize' for nil:NilClass

### ISSUE THREAD

**Issue by stulentsev** [rubyzip/rubyzip#290]
The file is opened correctly by MS Excel and system unzip tool, but not rubyzip. Changed extension to .zip for the convenience.

[test.zip](https://github.com/rubyzip/rubyzip/files/272505/test.zip)

``` 
     NoMethodError:
       undefined method `bytesize' for nil:NilClass
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:336:in `check_c_dir_entry_static_header_length'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:363:in `read_c_dir_entry'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:188:in `read_c_dir_entry'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:127:in `block in read_central_directory_entries'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:126:in `times'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:126:in `read_central_directory_entries'
     # /Users/sergio/.gem/ruby/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:138:in `read_from_stream'
     # /Users/sergio/.gem/ruby/2.3.0/gems/roo-2.3.1/lib/roo/excelx.rb:376:in `process_zipfile'
     # /Users/sergio/.gem/ruby/2.3.0/gems/roo-2.3.1/lib/roo/excelx.rb:48:in `initialize'
```

**Comment by shlima** [comment]
@stulentsev how did you solve the problem ?

**Comment by stulentsev** [comment]
@shlima 	hah, I wish I remembered :/

**Comment by stulentsev** [comment]
But since there's no comment from me, must have been a really stupid mistake on my part.
