### ISSUE TITLE
Regression from rubyzip 1.7.0 when creating ZIP files with Ruby <= 2.0

### ISSUE THREAD

**Issue by sschuberth** [rubyzip/rubyzip#291]
When working on [LicenseFinder](https://github.com/pivotal/LicenseFinder) I noticed a regression in rubyzip 2.0.0 compared to version 1.7.0. Notice how in [this build](https://travis-ci.org/sschuberth/LicenseFinder/builds/131644969) the tests fail, but just for Ruby <= 2.0. Then, after downgrading rubyzip to version 1.7.0, [this build](https://travis-ci.org/sschuberth/LicenseFinder/builds/131651607) shows how the tests pass.

The stacktrace of the original failure is:

```
1) LicenseFinder::Nuget#current_packages when there is a .nupkg file include the licenseUrl from the nuspec file
   Failure/Error:
     Zip::File.open('ObscureDependency.1.3.15.nupkg', Zip::File::CREATE) do |zipfile|
       zipfile.add('ObscureDependency.nuspec', 'ObscureDependency.nuspec')
     end
   TypeError:
     can't dup NilClass
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/pathname.rb:35:in `dup'   
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/pathname.rb:35:in `initialize'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file_system.rb:100:in `new'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file_system.rb:100:in `normalize_path'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file_system.rb:24:in `find'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file.rb:126:in `symlink?'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file.rb:39:in `exist?'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rubyzip-1.2.0/lib/zip/file.rb:412:in `ensure in on_success_replace'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rubyzip-1.2.0/lib/zip/file.rb:412:in `on_success_replace'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rubyzip-1.2.0/lib/zip/file.rb:310:in `commit'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rubyzip-1.2.0/lib/zip/file.rb:334:in `close'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rubyzip-1.2.0/lib/zip/file.rb:104:in `open'
   # ./spec/lib/license_finder/package_managers/nuget_spec.rb:108:in `block (5 levels) in <module:LicenseFinder>'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file_system.rb:90:in `call'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/file_system.rb:90:in `chdir'
   # /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/fakefs-0.6.7/lib/fakefs/dir.rb:73:in `chdir'
   # ./spec/lib/license_finder/package_managers/nuget_spec.rb:107:in `block (4 levels) in <module:LicenseFinder>'
```

**Comment by flavorjones** [comment]
Thanks for sending this! I'm hoping to get a new version of LF out in the next few days, and I'll merge this in.

**Comment by simonoff** [comment]
There is no support for ruby < 2.0
