### ISSUE TITLE
undefined method `to_binary_dos_time' for 2017-05-01 10:23:25 -0700:Time

### ISSUE THREAD

**Issue by jonyen** [rubyzip/rubyzip#327]
Hi,
Any idea how to resolve this error?

     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `to_binary_dos_time' for 2017-05-01 10:23:25 -0700:Time
     #   /Users/jonyen/.rvm/gems/ruby-2.3.0@global/gems/rubyzip-1.2.1/lib/zip/entry.rb:263:in `pack_local_entry'

Thank you.

**Comment by satishakumar** [comment]
I am facing same issue with rubyzip version 0.9.9.
`undefined method `to_binary_dos_time' for 2017-05-30 15:07:21 +0530:Time`

```
"/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_entry.rb:286:in `write_local_entry'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_output_stream.rb:147:in `block in update_local_headers'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:35:in `each'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:35:in `each'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_output_stream.rb:145:in `update_local_headers'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_output_stream.rb:64:in `close'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_output_stream.rb:50:in `ensure in open'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_output_stream.rb:50:in `open'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:216:in `block in commit'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:324:in `on_success_replace'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:214:in `commit'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:242:in `close'", 
     "/usr/local/lib/ruby/gems/2.1.0/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:92:in `open'", 
     "/app/zipper_job.rb:36:in `perform'", 
``` 
And my code is 
```
path="#{Rails.root}"
new_zip_name= "#{Time.now.to_i.to_s}"
archive = File.join(path,new_zip_name)+'.zip'
Zip::ZipFile.open(archive, 'w') do |zipfile| #Code breaking on this line
    #MY Code
end

```

**Comment by zm** [comment]
I'm not sure about details yet, but found in my case that
Once 'timecop' gem included and Zip::DOSTime.now return Time class not DOSTime class at Zip::Entry#initialize
and be in cannot call to_binary_dos_time.

**Comment by hainesr** [comment]
I think this should now be fixed - at least on HEAD - as I've gone through and made sure that all internal `Time` objects are now `DOSTime` objects.

Please shout if this is not the case.
