### ISSUE TITLE
can't dup NilClass with ruby 1.8.7 rubyzip-0.9.9 and Rails 2.3.5

### ISSUE THREAD

**Issue by dheeraj510** [rubyzip/rubyzip#368]
I've been seeing the **can't dup NilClass** error when creating a zip file. 

```
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `dup'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `dup'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `map'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_entry_set.rb:44:in `dup'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:75:in `initialize'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:228:in `commit'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:242:in `close'
/home/deploy/app/vendor/bundle/ruby/1.8/gems/rubyzip-0.9.9/lib/zip/zip_file.rb:92:in `open'
/home/deploy/app/app/models/digital_asset.rb:365:in `zip'
/home/deploy/app/app/models/digital_asset.rb:319:in `zip_assets_for'
/home/deploy/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/tmpdir.rb:129:in `mktmpdir'
/home/deploy/app/app/models/digital_asset.rb:315:in `zip_assets_for'
/home/deploy/app/lib/zip_queue.rb:9:in `perform'
```

we have sufficient ram size and disk space on the server.
Is there any Work-around for ruby 1.8.7 and Rails 2.3.5

**Comment by jdleesmiller** [comment]
It looks like you are using a very old version of this gem and ruby 1.8.7.

Support for rubies older than 2.0 was (controversially --- #256) dropped in https://github.com/rubyzip/rubyzip/commit/0cbae14c76d698840f4c60e62bda6ce0f30e6f37. 1.8.7 has been end of life [since 2014](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/), so I don't think it makes sense for us to start trying to support it again here.
