### ISSUE TITLE
Unsupported compression method 12

### ISSUE THREAD

**Issue by noff** [rubyzip/rubyzip#511]
I'm trying to extract an archive using `rubyzip`.

Simple file:

``` unzip.rb
require 'zip'

file = Zip::File.open "./1.zip"
entries = file.entries
entry = entries.first
destination_filename = entry.name.split('/').last # hmd15_lt_g06_se_c02_s04_p1.mp3
entry.extract(destination_filename)
```
Output:

```
$ ruby unzip.rb

Traceback (most recent call last):
       14: from /home/noff/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `<main>'
       13: from /home/noff/.rvm/rubies/ruby-2.7.0/bin/irb:23:in `load'
       12: from /home/noff/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
       11: from (irb):17
       10: from (irb):18:in `rescue in irb_binding'
        9: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/file.rb:341:in `extract'
        8: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:187:in `extract'
        7: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `create_file'
        6: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:620:in `open'
        5: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:621:in `block in create_file'
        4: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:537:in `get_input_stream'
        3: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/input_stream.rb:70:in `get_next_entry'
        2: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/input_stream.rb:137:in `open_entry'
        1: from /home/noff/.rvm/gems/ruby-2.7.0/gems/rubyzip-2.3.2/lib/zip/input_stream.rb:161:in `get_decompressor'
Zip::CompressionMethodError (Unsupported compression method 12)
```

Original zip file: https://drive.google.com/file/d/1Gt1yndsXywlIJyeqMSU6g9-VVegp9hV2/view?usp=sharing

Common extract in ubuntu console works well:

```
unzip 1.zip
```

Entries list works well:

```
> entries[0..5].each { |x| puts x.name }; nil
OPS/assets/audio/cards/hmd15_lt_g06_se_c02_s04_p1.mp3
OPS/assets/audio/cards/smil/06_ese_animalwisdom_04_en_us.smil
OPS/assets/css/baseline.css
OPS/assets/css/carousel.css
OPS/assets/css/custom.css
OPS/assets/css/epub_main.css
```

**Comment by hainesr** [comment]
Hello, Compression method 12 is bzip2 - we should probably improve that error message 😬 - which isn't included in rubyzip by default. To add bzip2 decompression support you can include the [rubyzip-bzip2 gem](https://github.com/rubyzip/rubyzip-bzip2), and then everything should just work.

**Comment by noff** [comment]
It's installed, but doesn't help:

```
➜  ziptest gem list rubyzip

*** LOCAL GEMS ***

rubyzip (2.3.2, 2.3.0)
rubyzip-bzip2 (0.0.1)
```

**Comment by hainesr** [comment]
OK, I'll transfer this issue over to the other repo then.
