### ISSUE TITLE
can't modify frozen String: ""

### ISSUE THREAD

**Issue by khiav223577** [rubyzip/rubyzip#561]
I am currently employing the `RUBYOPT="--enable-frozen-string-literal"` configuration for my project, which enforces the default freezing of all strings. However, I've encountered an issue with the compatibility of this setting in relation to the `rubyzip` library. I'm curious to know if there's a possibility that `rubyzip` will be updated to accommodate this configuration, especially considering the potential for strings to become automatically frozen by default in future versions of Ruby.

The error messages:
```
FrozenError:
  can't modify frozen String: ""
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/ioextras.rb:16:in `read'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/ioextras.rb:16:in `copy_stream_n'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/output_stream.rb:122:in `block in copy_raw_entry'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:599:in `open'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:599:in `get_raw_input_stream'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/output_stream.rb:119:in `copy_raw_entry'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:585:in `write_to_zip_output_stream'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:352:in `block (3 levels) in commit'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:38:in `block in each'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:351:in `block (2 levels) in commit'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/output_stream.rb:54:in `open'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:350:in `block in commit'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:454:in `block in on_success_replace'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:452:in `on_success_replace'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:349:in `commit'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:373:in `close'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:127:in `ensure in open'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyzip-2.3.2/lib/zip/file.rb:127:in `open'
# ~/.rvm/gems/ruby-3.0.0/gems/rubyXL-3.4.12/lib/rubyXL/parser.rb:7:in `parse'
```

**Comment by hainesr** [comment]
Hello,

Yes the next version of Rubyzip will support this by default. There is an Alpha out now that you can test, although beware that the API has changed as well: https://rubygems.org/gems/rubyzip/versions/3.0.0.alpha

Details on the API changes are here (WIP): https://github.com/rubyzip/rubyzip/wiki/Updating-to-version-3.x

Rob

**Comment by hlascelles** [comment]
Looks good 👍 

After a year since then do you think a release of `3.0.0` is good to go?
