### ISSUE TITLE
Tests CI of 2.4 branch fail to set up ruby on macOS

### ISSUE THREAD

**Issue by tikkss** [rubyzip/rubyzip#583]
Background
---

Hi, I'm a contributor to [red-data-tools/red-datasets: A RubyGem that provides common datasets](https://github.com/red-data-tools/red-datasets). red-datasets uses rubyzip 2.3. Thanks!

We are going a head to suppress "literal string will be frozen in the future" warning. Only the rubyzip warning remains.

We updating rubyzip to 3.x according to https://github.com/rubyzip/rubyzip/wiki/Updating-to-version-3.x#suggested-migration-path. We have reached stage 3 (Since 2.4 isn't officially released yet, we update to 2.4.rc1). Thanks for providing the suggested migration path.
> 1. Run your tests and satisfy yourself that everything is working as expected before going any further. (I know you know to do this, but this is a reminder for everyone else.)
> 2. Update your dependencies to use version 2.4 of the Rubyzip gem (coming soon!).
> 3. Run your tests - everything should still work as expected at this stage.

Most warnings have been resolved, but the following one still remains:

```console
/Users/zzz/.rbenv/versions/3.4.0-preview1/lib/ruby/gems/3.4.0+0/gems/rubyzip-2.4.rc1/lib/zip/extra_field/ntfs.rb:54: warning: literal string will be frozen in the future
```

I opened a pull request (GH-582) to resolve it. Then I found that the CI was failing. It is my first contribution to rubyzip, so awaiting approval the tests CI from a maintaner.

Error Details
---

Tests CI of 2.4 branch fail to setup ruby on macOS with Ruby 2.4 (forked repository's CI log):

https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:7
```console
Error: Error: CRuby < 2.6 does not support macos-arm64.
        Either use a newer Ruby version or use a macOS image running on amd64, e.g., macos-13 or macos-12.
        Note that GitHub changed the meaning of macos-latest from macos-12 (amd64) to macos-14 (arm64):
        https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

        If you are using a matrix of Ruby versions, a good solution is to run only < 2.6 on amd64, like so:
        matrix:
          ruby: ['2.4', '2.5', '2.6', '2.[7](https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:8)', '3.0', '3.1', '3.2', '3.3']
          os: [ ubuntu-latest, macos-latest ]
          # CRuby < 2.6 does not support macos-arm64, so test those on amd64 instead
          exclude:
          - { os: macos-latest, ruby: '2.4' }
          - { os: macos-latest, ruby: '2.5' }
          include:
          - { os: macos-13, ruby: '2.4' }
          - { os: macos-13, ruby: '2.5' }

        But of course you should consider dropping support for these long-EOL Rubies, which cannot even be built on recent macOS machines.
    at validateRubyEngineAndVersion (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65909:11)
    at setupRuby (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65[8](https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:9)01:15)
    at run (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65760:11)
    at /Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65[9](https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:10)57:40
    at /Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65959:3
    at Object.<anonymous> (/Users/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:65962:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:[10](https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:11))
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:[12](https://github.com/tikkss/rubyzip/actions/runs/10967885151/job/30458360683#step:3:13))
```

Maybe the following note is cause.

> Error: Error: CRuby < 2.6 does not support macos-arm64.
> Either use a newer Ruby version or use a macOS image running on amd64, e.g., macos-13 or macos-12.
> Note that GitHub changed the meaning of macos-latest from macos-12 (amd64) to macos-14 (arm64):
> https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/

2.4 branch requires at least Ruby 2.4 according to the following requirements of 2.4 branch:

https://github.com/rubyzip/rubyzip/blob/6ff40f7a78d85fad9f0f116f603c1c7f7ef2563f/README.md?plain=1#L25-L29

Solution
---

Should rubyzip specify macos-12 explicitly to require at least Ruby 2.4?:

```diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index e1e72aa..6bcaa70 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -7,12 +7,12 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu]
+        os: [ubuntu-latest]
         ruby: ['2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', jruby, truffleruby]
         include:
-          - os: macos
+          - os: macos-12
             ruby: '2.4'
-    runs-on: ${{ matrix.os }}-latest
+    runs-on: ${{ matrix.os }}
     steps:
     - name: Checkout rubyzip code
       uses: actions/checkout@v4
```

Or bump up required ruby version on macOS?:

```diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index e1e72aa..f483a91 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -11,7 +11,7 @@ jobs:
         ruby: ['2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', jruby, truffleruby]
         include:
           - os: macos
-            ruby: '2.4'
+            ruby: '2.6'
     runs-on: ${{ matrix.os }}-latest
     steps:
     - name: Checkout rubyzip code
```

I've confirmed that Tests CI pass in the both: [specify macos version explicitly](https://github.com/tikkss/rubyzip/commit/65098396862590d2ee0c42fce6f43c5ca5671062), [Bump up ruby version on macOS](https://github.com/tikkss/rubyzip/commit/44afa8570cc8664d8e35372618f7d501653d0f35)

Sorry, for the long message. We hope rubyzip 2.4 and 3.0 will be officially released soon, without rushing. Thanks!

**Comment by tikkss** [comment]
GitHub Actions's macos-12 runner will be fully retired by the December 3rd, 2024:
https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

Should rubyzip specify macos-13 explicitly to require at least Ruby 2.4?

**Comment by tikkss** [comment]
I've confirmed that Tests CI pass on macos-13:
https://github.com/tikkss/rubyzip/actions/runs/11086922577

**Comment by tikkss** [comment]
This issue was resolved by [Update earliest Ruby version for MacOS builds in CI](3d95a8204f76ed95970251a178426597f5f3ccef), so the Tests CI of 2.4 branch has been successful.

@hainesr Thanks! We hope rubyzip 2.4 and 3.0 will be officially released soon, without rushing.
